[project]
name = "doc-x-diff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ttkbootstrap>=1.10.1",
    "python-docx>=1.1.2",
    "redlines>=0.4.2",
    "pytest>=8.3.5",
    "htmldocx>=0.0.6",
    "markdown>=3.10.2",
    "tkinterdnd2>=0.4.3",
]
